[package]
name = "elemental-lang"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[[bin]]
name = "eltl"
path = "src/main.rs"

[lib]
name = "elemental"
path = "src/lib.rs"

[dependencies]
